apiVersion: v2
name: gcsm-store
description: A Helm chart for Google Cloud Secret Manager External Secrets
type: application
version: 0.1.6
appVersion: "0.20.4"
keywords:
  - vault
  - gcp
  - secrets
maintainers:
  - name: Michael Minichino
