apiVersion: v2
name: rdi-sys-config
description: A Helm chart for creating the RDI rdi-sys-config secret
type: application
version: 0.1.0
appVersion: "1.15.0"
keywords:
  - rdi
  - redis
  - secrets
maintainers:
  - name: Michael Minichino
