apiVersion: v2
name: redis-database
description: Deploy a REDB resource with the Redis Enterprise Operator
type: application
version: 0.1.17
appVersion: "8.0.2"
keywords:
  - kubernetes
  - redis
home: https://github.com/mminichino/helm-charts
sources:
  - https://github.com/mminichino/helm-charts
maintainers:
  - name: Michael Minichino
    url: https://github.com/mminichino/helm-charts
