#

name: "redb"
namespace: ""
username: "default"
password: ""
passwordSecret: ""
cluster: "redis-enterprise-cluster"
memory: "1GB"
replication: true
shards: 1
placement: sparse
port: 12000
eviction: noeviction
ossCluster: false
proxyPolicy: all-master-shards
persistence: aofEverySecond
version: "latest"
ossExporter:
  enabled: false
  image: "codelry/redis-exporter"
  version: "v1.79.0"
modules: []
ingress:
  type: "none"
  name: "haproxy"
tls:
  enabled: false
  certificates: []
dns:
  domain: ""
externalSecret:
  enabled: false
  store:
    kind: ClusterSecretStore
    name: ""
  key: ""
