{{- if .Values.global.vmMode }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
    product: rdi
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
        product: rdi
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fluentd
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/{{ .Values.fluentd.image.name }}:{{ or .Values.fluentd.image.tag .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: input-volume
              mountPath: /var/log/pods
            - name: output-volume
              mountPath: /fluentd/log
      initContainers:
        - name: chmod-init
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/{{ .Values.fluentd.image.name }}:{{ or .Values.fluentd.image.tag .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          command: ["chmod", "777", "{{ or .Values.fluentd.rdiLogsHostPath "/opt/rdi/logs" }}"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: output-volume
              mountPath: {{ or .Values.fluentd.rdiLogsHostPath "/opt/rdi/logs" }}
      volumes:
        - name: input-volume
          hostPath:
            path: {{ or .Values.fluentd.podLogsHostPath "/var/log/pods" }}
        - name: output-volume
          hostPath:
            path: {{ or .Values.fluentd.rdiLogsHostPath "/opt/rdi/logs" }}
{{- end }}
