apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rdi-api-binding
  labels:
    app: rdi-api
    product: rdi
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: rdi-api
roleRef:
  kind: Role
  name: rdi-api
  apiGroup: rbac.authorization.k8s.io
