apiVersion: v1
kind: Service
metadata:
  name: rdi-api
  labels:
    app: rdi-api
    product: rdi
    {{- with merge (.Values.api.service.labels | default dict) (.Values.global.labels | default dict) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge (.Values.api.service.annotations | default dict) (.Values.global.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: rdi-api
  ports:
    - name: rdi-api
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
  type: {{ .Values.api.service.type }}
