{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rdi-operator
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with merge (.Values.rbac.labels | default dict) (.Values.global.labels | default dict) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge (.Values.rbac.annotations | default dict) (.Values.global.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rdi-operator
subjects:
- kind: ServiceAccount
  name: rdi-operator
  namespace: {{ .Release.Namespace }}
{{- end -}}
