{{- if and .Values.webhooks.enabled (not .Values.certmanager.enabled) .Values.certJobs.enabled .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rdi-operator-jobs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    kubernetes.io/enforce-mountable-secrets: "true"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with merge (.Values.serviceAccount.labels | default dict) (.Values.global.labels | default dict) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge (.Values.serviceAccount.annotations | default dict) (.Values.global.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}