#
{{- if and .Values.tls.certificate .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-cert-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  certificate: {{ .Values.tls.certificate | b64enc }}
  key: {{ .Values.tls.key | b64enc }}
  name: {{ "proxy" | b64enc }}
{{- end }}
