#
{{- if and .Values.syncer.certificate .Values.syncer.key }}
apiVersion: v1
kind: Secret
metadata:
  name: syncer-cert-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  certificate: {{ .Values.syncer.certificate | b64enc }}
  key: {{ .Values.syncer.key | b64enc }}
  name: {{ "syncer" | b64enc }}
{{- end }}
