apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcsm-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.project | quote }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.serviceAccount }}
