apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-env
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  DATA_SOURCE_URI: "localhost:5432/{{ .Values.postgres.auth.database }}?sslmode=disable"
  DATA_SOURCE_USER: {{ .Values.postgres.auth.username | quote }}
