
{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    {{- with .Values.exporter.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace | default .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.exporter.serviceMonitor.interval }}
      path: /metrics
{{- end }}
