{{- if .Values.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-lb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.dns.domain }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres.{{ .Values.dns.domain }}"
  {{- end }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.loadBalancer.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}
