apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    onepasswordSDK:
      vault: {{ .Values.vault }}
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
