apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-dns
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: external-dns
          image: "{{ .Values.externalDns.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.externalDns.image.pullPolicy }}
          args:
            - --source=service
            - --source=ingress
            - --provider=oci
            - --policy=upsert-only
            - --txt-owner-id={{ .Values.externalDns.txtOwnerId }}
          volumeMounts:
            - name: config
              mountPath: /etc/kubernetes/
      volumes:
        - name: config
          secret:
            secretName: external-dns-config
