apiVersion: v2
name: redis-cluster
description: Deploy a REC resource with the Redis Enterprise Operator
type: application
version: 0.2.1
appVersion: "8.0.2"
keywords:
  - kubernetes
  - redis
home: https://github.com/mminichino/helm-charts
sources:
  - https://github.com/mminichino/helm-charts
maintainers:
  - name: Michael Minichino
    url: https://github.com/mminichino/helm-charts
dependencies:
  - name: redis-enterprise-operator
    version: 8.0.6-8
    repository: https://helm.redis.io
  - name: redis-password-operator
    version: 1.0.0
    repository: https://mminichino.github.io/redis-password-operator
