#

name: "redis-enterprise-cluster"
namespace: ""

license: ""

version: "8.0.2-17"
upgradePolicy: "latest"

username: "admin@redis.com"

node:
  count: 3
  cpu: "4"
  memory: 8Gi
  disk: 32Gi

ingress:
  enabled: false
  type: "haproxy"

storage:
  class: "standard"

dns:
  domain: ""

tls:
  name: "proxy"
  certificate: ""
  key: ""
  secret: ""
syncer:
  certificate: ""
  key: ""
  secret: ""

externalSecret:
  enabled: false
  store:
    kind: ClusterSecretStore
    name: ""
  key: ""
