apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oracle-vault-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    oracle:
      vault: {{ .Values.vault | quote }}
      principalType: Workload
      serviceAccountRef:
        name: {{ .Values.serviceAccount }}
        namespace: {{ .Release.Namespace }}
