apiVersion: v2
dependencies:
- alias: operator
  name: rdi-operator
  repository: file://charts/rdi-operator
  version: 0.0.0
- name: reloader
  repository: file://charts/reloader
  version: 1.1.1
description: A Helm chart for Kubernetes
name: rdi
type: application
version: 1.15.1
