apiVersion: v2
dependencies:
- alias: operator
  name: rdi-operator
  repository: file://../../operator/dist/chart
  version: 0.0.0
- name: reloader
  repository: https://stakater.github.io/stakater-charts
  version: 1.1.0
description: A Helm chart for Kubernetes
name: rdi
type: application
version: 1.15.0
