{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-database.passwordSecret" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
data:
  password: {{ include "redis-database.password" . | b64enc }}
{{- end }}
