{{- if .Values.ossExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Values.name }}-exporter"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}-exporter"
    release: prometheus
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}-exporter"
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
      relabelings:
        - targetLabel: namespace
          replacement: {{ .Values.namespace | default .Release.Namespace }}
          action: replace
        - targetLabel: database
          replacement: {{ .Values.name }}
          action: replace
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: kubernetes_namespace
          action: replace
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace | default .Release.Namespace }}
{{- end }}
