{{- if eq .Values.ingress.type "lb" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.name }}-lb-ip-config"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: redis-enterprise-operator
      restartPolicy: Never
      containers:
        - name: lb-ip-config
          image: docker.io/mminichino/kubectl:latest
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              set -e

              DOMAIN="{{ .Values.dns.domain }}"

              kubectl wait '--for=jsonpath={.status.loadBalancer.ingress[0].ip}' "service/{{ .Values.name }}-load-balancer" --timeout=10m -n {{ .Release.Namespace }}
              if [ -n "$DOMAIN" ]; then
                echo "Adding hostname to external-dns"
                kubectl annotate service "{{ .Values.name }}-load-balancer" "external-dns.alpha.kubernetes.io/hostname={{ .Values.name }}.$DOMAIN" --overwrite -n {{ .Release.Namespace }}
              fi
{{- end }}
