apiVersion: batch/v1
kind: Job
metadata:
  name: preinstall-job
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: redis-enterprise-operator
      restartPolicy: Never
      containers:
        - name: preinstall-job
          image: mminichino/kubectl:latest
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              set -e

              kubectl wait deployment/redis-enterprise-operator --for condition=available --timeout=5m -n {{ .Values.namespace | default .Release.Namespace }}
