apiVersion: v2
name: redis-di-cli
description: A Helm chart for running the RDI CLI
type: application
version: 0.1.3
appVersion: "1.15.0"
keywords:
  - rdi
  - redis
  - cli
maintainers:
  - name: Michael Minichino
