{{- if and .Values.metrics.enabled .Values.ingress.enabled }}
{{- $metricsPort := .Values.metrics.secure | ternary 8443 8080 -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdi-operator-metrics
  labels:
    app: rdi-operator-metrics
    product: rdi
    {{- with merge (.Values.ingress.labels | default dict) (.Values.global.labels | default dict) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge (.Values.ingress.annotations | default dict) (.Values.global.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $.Values.ingress.pathPrefix }}/metrics
            pathType: Prefix
            backend:
              service:
                name: rdi-operator-metrics
                port:
                  number: {{ $metricsPort }}
    {{- end }}
  {{- else }}
    - http:
        paths:
          - path: {{ .Values.ingress.pathPrefix }}/metrics
            pathType: Prefix
            backend:
              service:
                name: rdi-operator-metrics
                port:
                  number: {{ $metricsPort }}
  {{- end }}
{{- end }}
