apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reaadb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcsm-store
  target:
    name: reaadb-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: redb-demo-password
