apiVersion: v1
metadata:
  name: redis-enterprise-rceast
data:
  password: blg5b0J4cVI=
  username: ZGVtb0ByZWRpcy5jb20=
kind: Secret
type: Opaque
---
apiVersion: v1
metadata:
  name: redis-enterprise-rcwest
data:
  password: dFlJMkw1ZFM=
  username: ZGVtb0ByZWRpcy5jb20=
kind: Secret
type: Opaque
