apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.database }}-exporter-secret"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  redis-host: "{{ .Values.database }}.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local"
  redis-port: {{ .Values.port | quote }}
  redis-password: {{ .Values.password | quote }}
  redis-user: {{ .Values.username | quote }}
