apiVersion: v2
name: rdi-db-secrets
description: A Helm chart for creating the RDI source and target db secrets
type: application
version: 0.1.0
appVersion: "1.15.0"
keywords:
  - rdi
  - redis
  - secrets
maintainers:
  - name: Michael Minichino
