apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.name }}-github"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: "{{ .Values.name }}-github"
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: {{ .Values.repository }}
        sshPrivateKey: |-
          "{{ `{{` }} .ssh_private_key {{ `}}` }}"
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: {{ .Values.externalSecret.key }}
