apiVersion: v2
name: redis-exporter
description: Deploy the OSS Redis Exporter with the Redis Enterprise Operator
type: application
version: 0.1.4
appVersion: "v1.79.0"
keywords:
  - kubernetes
  - redis
home: https://github.com/mminichino/helm-charts
sources:
  - https://github.com/mminichino/helm-charts
maintainers:
  - name: Michael Minichino
    url: https://github.com/mminichino/helm-charts
